name: Build and push
on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build & Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        env:
          REGISTRY: harshalk91
          REPOSITORY: demo-flask
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
          docker push --all-tags $REGISTRY/$REPOSITORY

      - name: Run Trivy vulnerability scanner in image mode
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'harshalk91/demo-flask:latest'
          trivy-config: trivy.yaml


